language: java
os:
- linux
jdk:
- openjdk11
jobs:
  include:
  - stage: prepare
    script:
    - openssl aes-256-cbc -K $encrypted_92bb71d8d05e_key -iv $encrypted_92bb71d8d05e_iv
      -in signing_key.gpg.enc -out signing_key.gpg -d
    - gpg2 --batch --import signing_key.gpg
  - stage: test
    script: mvn test -B
  - stage: install
    script: mvn install --settings $TRAVIS_BUILD_DIR/settings.xml -B
env:
  global:
  - secure: P2UFtn2GndoWHNf6xehX79hhlbIqgUUdUZAurUt/QxOGhcz8k3tYJbfkxKTO57+QLkJFJWkjH+eX2Y1ZmDxewRTMPZRRoTx7yohOunOXPnjrJAFwSfT9oUAt/HAp2pNrZ+xPM1k0iYkJj0BxalPNAgxv2t6l5WEtAb/bNwzjvO2J5/3/YtmGfdM9QpzWjMWs2IGcJ2FQ36mDoRxWC+CKkNGq0hQJbVrojX/mr78GgIhnHbLgqr4lNp3ul2Vm4qHfRD04Q8eKJ8vdHJgi55ytxq8RU9zV8n3J5T4Q8zmlPTu6cP4q+siTL3HqfwghHz4rSGsmvVcsEyS+ctnhsaqHyoOgUIg+2WyIlW4rkYbmCCeuBT81JI941R/HHuExHazxKgj960KWkgtdzGMHLqN22V3wnFlc1WZben9h9YEYAymTrmRTUDAwZ8XohMJuMh9cvpR6YR9hXlyYXTwNZT6lm2cILbDU+vcn5fXVlOygHWWfIkKCvR6nD04XWvvPXG1aHzq8RoFJCfGFUplQh0ZM4VuNdDKdXpuMnptb29FYxUP+q7oYjtAswoahdgnA9f2OCDpP9UW8QuUxKpVJMgRPsuTTA0t1I37BCtjRQdry6zIs8nfYwwL5YIkj4kia6xDCMIeAHpOvQlhRzi3+w+hvp54lOubYMidFmKHJMZBgSn8=
  - secure: QYJdo//n9gzrqrH8nwhkbt3m4c9jNmhKarR372SgJD4ro/y/sF/EFTAsGrDgKeMYYA4esD5PsZJhmoZQfXbgQyzILJeR1P8rpcXao8vsgUGYkI22ZA5TcrHgEgTxQdWpodpPzF8PstX0qm7emd6AY4iX5GsSHRX9QkjBue2VZka+tYig4Jy2LRp70NOYwhBFa21ZygN8g1zRMIPL8GKe98PdUK/sZq5MO9lRlV5p8e5TFSOu1Znq2XkaCl/SBWhtkVQc+nChUorXtjm9yT+ekq/qShrTOZhkskJkqGU91qXrQQvWk7CNH4SnVzgZ48EVsLg/DmfmI17+JKwYIxV+tzj6451419ajtlK1h9OAnMoyoL4dZG7Ft8XP0FGh5GL69/EKrcsB7m2UJ6lM4nuNjrb5xiR7GuoAnNQ+cYWirlQ9T1+Y/VnENJBkH5+EDcGmSPtF/XPlxa/57u8O4xa4VKmDcZc1He4uQQ+/t6N/Vf+WpkoMTAFtwwsCHDOFgwvKfe7CUnC42ZLGtJYXemzp4zjzLKvRNZdptj0K7+5ohPW3cQDIO74FSXMEA7MK6VZC3yu5udtXB/lCqJxurtAZFq0tzdM5wqQ6TOT5Ece7mhSmqWMQdL0iT79JxHbpjUSFwpVFLNPCjRncrMq/lR6J5neEAalhC5brsNl81M7rWEU=
  - secure: Shy7RTEuqROyMgaA9eusNK41up0PF7Z9brqDYomsrOOvroTKUAKdFeCIIXWCVBvJ/lVrxm4kngKM8bcqMNZz47DK+90jD9aUawPDv70Ml6QRioBpvahng3R0mPFnnLrx4fpVsLkX/zOlI78RmxAER3cQSSFrHSc8y7qEwsn3k1o95U/q3Vp1tM8AR1h5kTtE2Ev0IocYRDnFZfO3bWa1E6wrbqftxZ6HpJYJKkTZoBwtap1unWm9ggAblw1/0i8inn3vDRKzVNCn6qR9qoZv1jONf187GvmlVk65PJOGt0LuoI1MTwhkQNo+hIFqFeuzMl38w76/ugxKtA1Ejjoq4SdplniwzWQUIiLeSRFXCO4M9pB2A3gssICfLbgaUaDiaO4NhJv18hN63Npn+8vC1avk8nb0+kRanFXURX9+HwXyFyjAhbDkbysyzzKtr06P+AV5G0NJbalqRdqy8R4w4CD95ZR467rsrGryXvmBwIGPNFyuc7JIABnAWg820dzgCgPwoy/ymqYtw7qw2Hn4ewaTKIKVmdVfJblUH8mzLunp0QQiytT6ReLJRWvY7xOK9L8pBrt7YMbRvIeFs/XgYWt9XzpVtZVetbtsTdeinUy0cxsKFuXx1UG5pQr9weNBawQigCttoclp/KuckwULYBgLsC3/HvhaQRKXgtgfNOc=

